kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    karpenter.sh/capacity-type: spot
- role: worker
  labels:
    karpenter.sh/capacity-type: on-demand
